apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: shiksha-workspace
  name: shiksha-workspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shiksha-workspace
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: shiksha-workspace
    spec:
      containers:
      - image: ${ECR_REPOSITORY}:${IMAGE_TAG}
        imagePullPolicy: "Always"
        name: workspace-shiksha
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
      envFrom:
        - configMapRef:
            name: workspace-service-config
      
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: shiksha-workspace
spec:
  type: ClusterIP
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: shiksha-workspace
